services:
  web:
    image: gdmurray/trackkeeper:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=/run/secrets/redis_url
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "${LOKI_URL}"
    #     loki-external-labels: "job=dockerswarm,environment=production,service=web"

  celery_worker:
    image: gdmurray/trackkeeper:latest
    command: celery -A app.core.celery_app worker -Q default,cron_tasks
      --loglevel=info --max-tasks-per-child=2
    environment:
      - REDIS_URL=/run/secrets/redis_url
    env_file:
      - .env
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "celery", "-A", "app.core.celery_app", "inspect", "ping", "-d", "celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "${LOKI_URL}"
    #     loki-external-labels: "job=dockerswarm,environment=production,service=celery_worker"

  celery_beat:
    image: gdmurray/trackkeeper:latest
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - REDIS_URL=/run/secrets/redis_url
    env_file:
      - .env
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "celery", "-A", "app.core.celery_app", "inspect", "ping", "-d", "celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "${LOKI_URL}"
    #     loki-external-labels: "job=dockerswarm,environment=production,service=celery_beat"

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  flower:
    image: gdmurray/trackkeeper:latest
    command: celery -A app.core.celery_app flower --port=5555
      --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} --broker=${REDIS_URL}
      --broker_api=${REDIS_URL}
    ports:
      - 5555:5555
    environment:
      - REDIS_URL=/run/secrets/redis_url
      - FLOWER_USER=/run/secrets/flower_user
      - FLOWER_PASSWORD=/run/secrets/flower_password
    env_file:
      - .env
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "${LOKI_URL}"
    #     loki-external-labels: "job=dockerswarm,environment=production,service=flower"
