version: '3.8'

services:
  web:
    image: gdmurray/trackkeeper:latest
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=/run/secrets/redis_url
    secrets:
      - spotify_client_id
      - spotify_client_secret
      - supabase_url
      - supabase_key
      - redis_url
      - flower_user
      - flower_password
    deploy:
      replicas: 1
    depends_on:
      - redis

  celery_worker:
    image: gdmurray/trackkeeper:latest
    command: celery -A app.core.celery_app worker -Q default,cron_tasks --loglevel=info --max-tasks-per-child=2
    environment:
      - REDIS_URL=/run/secrets/redis_url
    secrets:
      - spotify_client_id
      - spotify_client_secret
      - supabase_url
      - supabase_key
      - redis_url
      - flower_user
      - flower_password
    deploy:
      replicas: 2
    depends_on:
      - redis

  celery_beat:
    image: gdmurray/trackkeeper:latest
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - REDIS_URL=/run/secrets/redis_url
    secrets:
      - spotify_client_id
      - spotify_client_secret
      - supabase_url
      - supabase_key
      - redis_url
      - flower_user
      - flower_password
    deploy:
      replicas: 1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1

  flower:
    image: your-registry/your-app:latest
    command: celery -A app.core.celery_app flower --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} --broker=${REDIS_URL} --broker_api=${REDIS_URL}
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=/run/secrets/redis_url
      - FLOWER_USER=/run/secrets/flower_user
      - FLOWER_PASSWORD=/run/secrets/flower_password
    secrets:
      - spotify_client_id
      - spotify_client_secret
      - supabase_url
      - supabase_key
      - redis_url
      - flower_user
      - flower_password
    deploy:
      replicas: 1
    depends_on:
      - redis
      - celery_worker

secrets:
  spotify_client_id:
    external: true
  spotify_client_secret:
    external: true
  supabase_url:
    external: true
  supabase_key:
    external: true
  redis_url:
    external: true
  flower_user:
    external: true
  flower_password:
    external: true

