name: Deploy Actions

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: gdmurray
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gdmurray/trackkeeper:latest
          context: backend
          file: Dockerfile
          platform: linux/amd64
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        id: docker_build

      - name: Move Docker Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "app"
          passphrase: "${{ secrets.SSH_PASSPHRASE }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            echo "Creating .env file"
            cat > ~/trackkeeper/.env << EOF
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            FLOWER_USER=greg
            FLOWER_PASSWORD=${{ secrets.FLOWER_PASSWORD }}
            SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            EOF

            echo ".env file created with secrets."

            cd ~/trackkeeper

            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/mma-oracle-github-deploy-key
            git reset --hard HEAD
            git pull origin main

            # Pull latest images
            docker-compose -f docker-compose.prod.yml pull

            # Interpolate .env file and deploy the stack
            # The <(...) syntax creates a temporary file from the output of docker-compose config which docker stack deploy can use
            docker stack deploy -c <(docker-compose -f docker-compose.prod.yml config | sed -E 's/published: "([0-9]+)"/published: \1/' | sed '/^name: trackkeeper/d') trackkeeper
